added search persistence when moving from bookmark to home
creativecommons/ccsearch-browser-extension pull request #226
Opened 2020-04-20 12:51 UTC by techievivek

Fixes #224 

**Description**
Added search persistency when moving from bookmark context to home.

**Other information**

**Checklist:**
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

2020-04-20 12:58 UTC, techievivek commented
@makkoncept The issue was when we clicked on the home button, it called the function `loadStoredSearch`, which basically first checks whether the other setting `enableSearchStorage` is checked or not, so when moving from bookmark to home, it creates a problem.
Also, there was issue when someone searches a `query`, so I had to remove the condition and store the result no matter what.
And created 2 different functions, one when the home button gets clicked and the other when the extension is open.
Please verify it.

2020-04-20 15:15 UTC, makkoncept commented
@techievivek Thanks for the PR! I will check it out soon.

2020-04-21 12:30 UTC, makkoncept requested changes
This works fine but I have found a very subtle bug. When the user searches for a query that returns an empty result then the localStorage is not updated as the result array is empty. This means that after switching from the bookmarks section, the last correct result will be loaded. That's good. But, below the loaded images in this particular case, the "No image found" message is still present. Please refer to the gif below:


![ezgif com-optimize](https://user-images.githubusercontent.com/34679965/79866041-c8f7cd80-83f9-11ea-98bb-c67ef05e479d.gif)

2020-04-21 12:30 UTC, makkoncept commented on src/popup/popup.js
> +async function loadStoredSearchOnLoad() {
`loadStoredSearchOnInit()`  sounds like a better name for this function.

2020-04-21 13:33 UTC, techievivek commented
@makkoncept Thank you for pointing out the bug, I will fix the bug soon and update the PR.

2020-04-21 18:06 UTC, techievivek commented
> This works fine but I have found a very subtle bug. When the user searches for a query that returns an empty result then the localStorage is not updated as the result array is empty. This means that after switching from the bookmarks section, the last correct result will be loaded. That's good. But, below the loaded images in this particular case, the "No image found" message is still present. Please refer to the gif below:
> 
> ![ezgif com-optimize](https://user-images.githubusercontent.com/34679965/79866041-c8f7cd80-83f9-11ea-98bb-c67ef05e479d.gif)

The issue was if an invalid input was searched, the localStorage wasn't cleared, and thus moving from Bookmark to Home left with the same result, so once the input has been validated along with other parameters, I clear the localStorage. Please have a look at updated PR.

2020-04-22 16:50 UTC, makkoncept commented
After switching from the bookmarks section to the search section, instead of the "No images found" message, the default search section message can be shown.
![ezgif com-video-to-gif (5)](https://user-images.githubusercontent.com/34679965/80009080-34b76480-84e6-11ea-822b-b276180805dd.gif)

2020-04-22 17:34 UTC, techievivek commented
@makkoncept I will go through it and update the PR. Thank you

2020-04-24 14:56 UTC, techievivek commented
@makkoncept Please have a look at the Updated PR, I have added the required changes.
![ezgif com-video-to-gif(4)](https://user-images.githubusercontent.com/35863227/80226106-948a4880-8669-11ea-99e4-18d631d18657.gif)

2020-04-24 20:31 UTC, makkoncept approved these changes

2020-04-24 20:33 UTC, merged