Added the feature of sharing the images with Tumblr
creativecommons/ccsearch-browser-extension pull request #44
Opened 2019-11-27 13:19 UTC by VarthanV

**Description**
        I have been using the extension for a while and I have been sharing images regularly from the extension. I use Tumblr regularly to share my thoughts whenever  I have to share the image it becomes difficult for me since the extension doesn't have an option to share it in Tubmlr directly as it has for the other platforms. So i implemented the feature of sharing the image directly to the Tumblr platform. 

![Screenshot 2019-11-27 at 6 49 10 PM](https://user-images.githubusercontent.com/39593586/69726460-a57c6f80-1146-11ea-9989-752dbd04841e.png)

2019-11-28 12:43 UTC, makkoncept requested changes
Hi @VarthanV. Thanks for this PR.
I have checked the changes locally and everything is working fine. But the changes are violating eslint rules and therefore, are giving linting errors. I have marked a couple of them here. Please fix those. 

You can run `npm run lint` to run the lint. Or you can also install an Eslint extension for your editor to view the errors and warnings.

2019-11-28 12:43 UTC, makkoncept commented on src/popup/infoPopupModule.js
> +function getTumblrShareLink(sourceLink,imageLink) {
Require space after the `,`. [comma-spacing](https://eslint.org/docs/rules/comma-spacing)

2019-11-28 12:43 UTC, makkoncept commented on src/popup/infoPopupModule.js
> +  let creatorUrl = "Not Available";
The string must use single quotes.

2019-11-28 12:59 UTC, VarthanV commented
Sir Thank you four your review, I  have made the necessary changes sir by using the methods that you suggested above . Thank You!

2019-11-28 13:45 UTC, VarthanV commented
Sorry for the Inconvenience sir, I have reviewed it and fixed all the eslint errors! Thank You!

2019-12-01 04:37 UTC, VarthanV commented
Sir I have made the changes will my commit be merged?

2019-12-02 18:58 UTC, makkoncept commented
@VarthanV you need to remove the "Default Filters" heading on the options page. There is no need of that.

2019-12-04 13:15 UTC, VarthanV commented
Sir I have removed the default filters heading  please do review my change

2019-12-04 15:17 UTC, makkoncept commented
@VarthanV you have to also push the changes, because they are not showing in this PR.
The last commit from your side has been "Fixed ESLint errors".

2019-12-04 15:33 UTC, VarthanV commented
I  have made the necessary changes @makkoncept

2019-12-04 16:41 UTC, makkoncept commented
@VarthanV you still don't have removed the "Default filters" heading in `options.html`. Also, please write better commit message.

2019-12-05 01:45 UTC, VarthanV commented
@makkoncept  sir .I have made the changes for sure now and added a valid Commit message

2019-12-05 09:23 UTC, merged