Add paragraph styles to main extension popup
creativecommons/ccsearch-browser-extension pull request #50
Opened 2019-12-01 14:22 UTC by sharmaaditya570191

Fixes #38 

**Description**
Added CC vocabulary paragraph styles to main extension popup.

**Checklist:**
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [ ] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

2019-12-02 19:07 UTC, makkoncept commented
@sharmaaditya570191 please paste the screenshots of the changes

2019-12-03 13:39 UTC, sharmaaditya570191 commented
Hi @makkoncept .I would add the screenshots in a while. Thanks.

2019-12-04 14:31 UTC, sharmaaditya570191 commented
**Before**
![Screenshot from 2019-12-04 19-59-56](https://user-images.githubusercontent.com/42587159/70150902-cc035300-16d0-11ea-9f28-fa6b669b6436.png)

**After**
![Screenshot from 2019-12-04 20-01-48](https://user-images.githubusercontent.com/42587159/70150910-ce65ad00-16d0-11ea-9da6-9f3223a7a060.png)

2019-12-04 14:32 UTC, sharmaaditya570191 commented
Hi @makkoncept . Please suggest if something else is to be changed here.

2019-12-05 02:54 UTC, ritesh-pandey commented
@sharmaaditya570191 I think we will have to make changes [here](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/utils.js#L34) as well.

2019-12-05 17:45 UTC, makkoncept requested changes
I have added a comment. Also, @ritesh-pandey pointed out a valid point. Please make the necessary changes.

2019-12-05 17:45 UTC, makkoncept commented on src/popup/popup.html
> +          <div class="row vocab paragraph inherit-colored">
Add these classes directly to the paragraph tag.

2019-12-06 13:51 UTC, sharmaaditya570191 commented
**After Changes**

![Screenshot from 2019-12-06 19-25-03](https://user-images.githubusercontent.com/42587159/70327774-8922b600-185d-11ea-8f6e-1f30df36a237.png)

2019-12-06 19:16 UTC, merged