Added paragraph and heading styles to bookmark section
creativecommons/ccsearch-browser-extension pull request #51
Opened 2019-12-01 15:23 UTC by sharmaaditya570191

Fixes #39 

**Description**  
Added paragraph and heading styles to bookmark section.  

**Checklist:**
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [ ] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

2019-12-02 19:06 UTC, makkoncept commented
@sharmaaditya570191 please add the screenshots of the changes

2019-12-03 12:21 UTC, sharmaaditya570191 commented
Hi @makkoncept I will add the screenshot of the changes soon.

2019-12-04 14:53 UTC, sharmaaditya570191 commented
**Before**
![Screenshot from 2019-12-04 20-12-35](https://user-images.githubusercontent.com/42587159/70152776-d3782b80-16d3-11ea-8648-ba695c92f58b.png)

**After**
![Screenshot from 2019-12-04 20-24-36](https://user-images.githubusercontent.com/42587159/70152781-d541ef00-16d3-11ea-8832-d708a3164f8b.png)

2019-12-04 14:54 UTC, sharmaaditya570191 commented
Hi @makkoncept . I have made final changes and added screenshot. Please have a look.

2019-12-05 17:39 UTC, makkoncept requested changes

2019-12-05 17:39 UTC, makkoncept commented on src/popup/popup.html
> +          <div class="row vocab paragraph inherit-colored negative-indicating">
Please add these classes to the paragraph element, not to the div.

2019-12-05 17:39 UTC, makkoncept commented on src/popup/popup.html
> +        <div class="text-align-center vocab heading">
Add the class to the heading element, not to the div.
Also, as your screenshot shows, the current size of heading is too small, please adjust it accordingly.

2019-12-06 13:35 UTC, sharmaaditya570191 commented
**After changes** 
![Screenshot from 2019-12-06 19-06-42](https://user-images.githubusercontent.com/42587159/70326762-537ccd80-185b-11ea-9745-8402dae2785c.png)

2019-12-06 19:22 UTC, makkoncept commented
The issue which this PR tries to solve also says to remove the redundant CSS styles from `_bookmarks.scss`. Please do that.

Remove the h2 styles. [see here](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/popup/sass/components/_bookmarks.scss#L11)

2019-12-07 04:38 UTC, sharmaaditya570191 commented
![Screenshot from 2019-12-07 10-14-04](https://user-images.githubusercontent.com/42587159/70369053-6930d800-18d9-11ea-9b80-8eb28fabb870.png)

2019-12-09 08:49 UTC, sharmaaditya570191 commented
Please have a look @makkoncept

2019-12-10 13:26 UTC, merged